apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: weather-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"      # minimum CPU guaranteed; used by HPA
            memory: "128Mi"  # optional
          limits:
            cpu: "500m"      # maximum CPU container can use
            memory: "256Mi"
